/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package login1;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author 34680
 */
public class login_ extends javax.swing.JFrame {
Connection con= bbdd.conectbd();
    
    
    PreparedStatement ps=null;
    ResultSet rs=null;
    public login_() {
        initComponents();
        this.setLocationRelativeTo(null);
         bbdd.conectbd();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jpanelogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jusuario = new javax.swing.JLabel();
        txtusuario = new javax.swing.JTextField();
        jcontra = new javax.swing.JLabel();
        txtcontra = new javax.swing.JPasswordField();
        btt_loguear = new javax.swing.JButton();
        btt_newusuario = new javax.swing.JButton();
        btt_selector = new javax.swing.JButton();
        mostrar = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jminimizar = new javax.swing.JLabel();
        jcerrar = new javax.swing.JLabel();
        jlabel_login = new javax.swing.JLabel();
        btt_cambiocolor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        archivos_bar = new javax.swing.JMenu();
        ayuda_bar = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jpanelogin.setBackground(new java.awt.Color(149, 175, 192));
        jpanelogin.setForeground(new java.awt.Color(255, 255, 255));
        jpanelogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpaneloginMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Introduzca credenciales:");

        jusuario.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jusuario.setText("Usuario:");

        txtusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jcontra.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jcontra.setText("Contraseña:");

        txtcontra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btt_loguear.setBackground(new java.awt.Color(19, 15, 64));
        btt_loguear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btt_loguear.setForeground(new java.awt.Color(255, 255, 255));
        btt_loguear.setText("LOGUEAR");
        btt_loguear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_loguearActionPerformed(evt);
            }
        });

        btt_newusuario.setBackground(new java.awt.Color(19, 15, 64));
        btt_newusuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btt_newusuario.setForeground(new java.awt.Color(255, 255, 255));
        btt_newusuario.setText("CREAR USUARIO");
        btt_newusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_newusuarioActionPerformed(evt);
            }
        });

        btt_selector.setBackground(new java.awt.Color(19, 15, 64));
        btt_selector.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btt_selector.setForeground(new java.awt.Color(255, 255, 255));
        btt_selector.setText("ABRIR FICHEROS");
        btt_selector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_selectorActionPerformed(evt);
            }
        });

        mostrar.setBackground(new java.awt.Color(149, 175, 192));
        mostrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        mostrar.setText("Mostrar");
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        mostrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mostrarKeyTyped(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(19, 15, 64));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jminimizar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jminimizar.setForeground(new java.awt.Color(255, 255, 255));
        jminimizar.setText("_");
        jminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jminimizarMouseClicked(evt);
            }
        });

        jcerrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcerrar.setForeground(new java.awt.Color(255, 255, 255));
        jcerrar.setText("X");
        jcerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcerrarMouseClicked(evt);
            }
        });

        jlabel_login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jlabel_login.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_login.setText("LOGIN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(jlabel_login, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(207, 207, 207)
                .addComponent(jminimizar)
                .addGap(20, 20, 20)
                .addComponent(jcerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jminimizar)
                    .addComponent(jcerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabel_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        btt_cambiocolor.setBackground(new java.awt.Color(19, 15, 64));
        btt_cambiocolor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btt_cambiocolor.setForeground(new java.awt.Color(255, 255, 255));
        btt_cambiocolor.setText("CAMBIAR COLOR");
        btt_cambiocolor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btt_cambiocolorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpaneloginLayout = new javax.swing.GroupLayout(jpanelogin);
        jpanelogin.setLayout(jpaneloginLayout);
        jpaneloginLayout.setHorizontalGroup(
            jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpaneloginLayout.createSequentialGroup()
                .addGroup(jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpaneloginLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcontra)
                            .addComponent(jusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtcontra))
                        .addGap(39, 39, 39)
                        .addComponent(mostrar))
                    .addGroup(jpaneloginLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpaneloginLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btt_newusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_loguear, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_selector, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btt_cambiocolor, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpaneloginLayout.setVerticalGroup(
            jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpaneloginLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel1)
                .addGap(64, 64, 64)
                .addGroup(jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jusuario)
                    .addComponent(txtusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jpaneloginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcontra)
                    .addComponent(txtcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar))
                .addGap(42, 42, 42)
                .addComponent(btt_loguear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btt_newusuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btt_selector)
                .addGap(18, 18, 18)
                .addComponent(btt_cambiocolor, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        archivos_bar.setText("Archivos");
        jMenuBar1.add(archivos_bar);

        ayuda_bar.setText("Ayuda");
        jMenuBar1.add(ayuda_bar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpanelogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcerrarMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jcerrarMouseClicked

    private void jminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jminimizarMouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jminimizarMouseClicked

    int xx, xy;
    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // TODO add your handling code here:
        xx= evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        // TODO add your handling code here:
        int x= evt.getXOnScreen();
        int y = evt.getYOnScreen();
        
        this.setLocation(x-xx, y-xy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void mostrarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mostrarKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mostrarKeyTyped

    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        // TODO add your handling code here:
        if (mostrar.isSelected()) {
            txtcontra.setEchoChar((char)0);
        } else {
            txtcontra.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void btt_newusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_newusuarioActionPerformed
        usuario_nuevo g= new usuario_nuevo();
        g.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btt_newusuarioActionPerformed

    private void btt_loguearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_loguearActionPerformed
        // TODO add your handling code here:
        String us = txtusuario.getText();
        String contra = txtcontra.getText();
        String jean="SELECT * FROM login WHERE usuario=? AND contraseña=?";

        try {
            ps=con.prepareStatement(jean);
            ps.setString(1, txtusuario.getText());
            ps.setString(2, txtcontra.getText());
            rs=ps.executeQuery();
            if(rs.next()){
                bienvenido f = new bienvenido();
                f.setVisible(true);
                this.setVisible(false);
            }else if(us.equals("jean") && contra.equals("hola")){

                bienvenido f = new bienvenido();
                f.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Error en el campo contraseña o campo usuario.");
                login_ l = new login_();
                l.setVisible(true);
                this.setVisible(false);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btt_loguearActionPerformed

    private void btt_cambiocolorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_cambiocolorActionPerformed
        // TODO add your handling code here:
        Color color= JColorChooser.showDialog(jpanelogin, "Elige color", Color.yellow);
        jpanelogin.setBackground(color);
        jpanelogin.setOpaque(true);
        
    }//GEN-LAST:event_btt_cambiocolorActionPerformed

    private void jpaneloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpaneloginMouseClicked
        // TODO add your handling code here:
        cambiocolor cc = new cambiocolor(this, true);
        cc.setVisible(true);
       
        jpanelogin.setBackground(cc.getBackground());
        jpanelogin.setOpaque(true);
        
    }//GEN-LAST:event_jpaneloginMouseClicked

    private void btt_selectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btt_selectorActionPerformed
        // TODO add your handling code here:
        selector_ficheros sl= new selector_ficheros();
        sl.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btt_selectorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu archivos_bar;
    private javax.swing.JMenu ayuda_bar;
    private javax.swing.JButton btt_cambiocolor;
    private javax.swing.JButton btt_loguear;
    private javax.swing.JButton btt_newusuario;
    private javax.swing.JButton btt_selector;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jcerrar;
    private javax.swing.JLabel jcontra;
    private javax.swing.JLabel jlabel_login;
    private javax.swing.JLabel jminimizar;
    private javax.swing.JPanel jpanelogin;
    private javax.swing.JLabel jusuario;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JPasswordField txtcontra;
    private javax.swing.JTextField txtusuario;
    // End of variables declaration//GEN-END:variables
}
